### ISSUE TITLE
Limit number of listeners

### ISSUE THREAD

**Issue by rscardinho** [talyssonoc/emittr#21]
Add a constraint to limit how many listeners can be added to the list.
Thinking about the best way to configure this value 🤔

**Comment by talyssonoc** [comment]
we could have a method to use like this:

``` ruby
class MyEmitter
   includes Emittr::Events

   max_listeners 3
end
```

**Comment by rscardinho** [comment]
yeah, I thought about something like this and seems to be good enough to get this done 🚀
